In [7]:
import numpy as np
import torch as T
device = 'cpu'

In [8]:
seed = 0xEDA

In [9]:
print("Создадим данные")
T.manual_seed(seed)
np.random.seed(seed)

# 1. Модельные данные для обучения
train_x = np.array([
    [1.5, 2.5], [3.5, 4.5], [6.5, 6.5],
    [4.5, 1.5], [5.5, 3.5], [7.5, 5.5]], dtype=np.float32)
train_y = np.array([1, 1, 1, 0, 0, 0], dtype=np.compat.long)

Создадим данные


In [10]:
print("Превратим в тензоры:")
print(train_x)
print(train_y)

train_x = T.tensor(train_x, dtype=T.float32).to(device)
train_y = T.tensor(train_y, dtype=T.long).to(device)

# print(type(train_x))

Превратим в тензоры:
[[1.5 2.5]
 [3.5 4.5]
 [6.5 6.5]
 [4.5 1.5]
 [5.5 3.5]
 [7.5 5.5]]
[1 1 1 0 0 0]


In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
from lr import LogisticRegression

In [23]:
my_lr = LogisticRegression(device)

lrn_rate = 0.05
indices = np.arange(6)

w = my_lr.fit(
    train_x,
    train_y,
    lrn_rate,
    indices,
    100,
    0)

print(w)

epoch =    0    loss = 0.2475
epoch =   10    loss = 0.1234
epoch =   20    loss = 0.0772
epoch =   30    loss = 0.0552
epoch =   40    loss = 0.0429
epoch =   50    loss = 0.0349
epoch =   60    loss = 0.0294
epoch =   70    loss = 0.0254
epoch =   80    loss = 0.0223
epoch =   90    loss = 0.0198
tensor([-1.3765,  1.5673], grad_fn=<AddBackward0>)
