In [1]:
import numpy as np
import torch as T
device = 'cpu'

In [2]:
seed = 0xEDA

In [48]:
print("Создадим данные")
T.manual_seed(seed)
np.random.seed(seed)

# 1. Модельные данные для обучения
# train_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5], [1.0, 2.0], [2.5, 7.5], [3.0, 9.0], [4.5, 11.5], [2.0, 6.0],
#     [4.5, 1.5], [5.5, 3.5], [7.5, 5.5], [4.5, 2.5], [8.0, 2.5], [6.5, 3.5], [8.5, 4.5], [5.0, 2.0]], 
#     dtype=np.float32)
# train_y = np.array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.compat.long)

# train_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5], [1.0, 2.0], [2.5, 7.5],
#     [4.5, 1.5], [6.5, 2.5], [8.5, 2.5], [4.5, 2.5], [8.0, 2.5]], dtype=np.float32)
# train_y = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=np.compat.long)

# train_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5],
#     [4.5, 1.5], [5.5, 3.5], [7.5, 5.5]], dtype=np.float32)
# train_y = np.array([1, 1, 1, 0, 0, 0], dtype=np.compat.long)


train_x = np.array([
    [1, 2], [1, 3], [1, 4], [1, 5], [2, 3], [2, 4], [2, 5], [3, 4], [3, 5], [4, 5],
    [2, 1], [3, 1], [4, 1], [5, 1], [3, 2], [4, 2], [5, 2], [4, 3], [5, 3], [5, 4]], dtype=np.float32)
train_y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=np.compat.long)


# 2. Тестируемые данные
test_x = np.copy(train_x)
test_y = np.copy(train_y)
# test_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5],
#     [4.5, 1.5], [5.5, 3.5], [7.5, 5.5]], dtype=np.float32)
# test_y = np.array([1, 1, 1, 0, 0, 0], dtype=np.compat.long)

Создадим данные


In [49]:
print("Превратим в тензоры:")
print(train_x)
print(train_y)

train_x = T.tensor(train_x, dtype=T.float32).to(device)
train_y = T.tensor(train_y, dtype=T.long).to(device)

test_x = T.tensor(test_x, dtype=T.float32).to(device)
test_y = T.tensor(test_y, dtype=T.long).to(device)

# print(type(train_x))

Превратим в тензоры:
[[1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [3. 4.]
 [3. 5.]
 [4. 5.]
 [2. 1.]
 [3. 1.]
 [4. 1.]
 [5. 1.]
 [3. 2.]
 [4. 2.]
 [5. 2.]
 [4. 3.]
 [5. 3.]
 [5. 4.]]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [50]:
from sklearn.linear_model import LogisticRegression
from lr import MyLogisticRegression

In [54]:
my_lr = MyLogisticRegression(device)

lrn_rate = 0.05
indices = np.arange(len(test_x))

w, b = my_lr.fit(
    train_x,
    train_y,
    lrn_rate,
    indices,
    1000,
    0)

print(my_lr.w, my_lr.b)

tensor([ 3.2468, -3.2468], grad_fn=<AddBackward0>) tensor([1.7380e-05], requires_grad=True)


In [55]:
p = my_lr.predict(test_x)

In [56]:
print(p)

[3.7442554e-02 1.5108299e-03 5.8854512e-05 2.2894865e-06 3.7442382e-02
 1.5108221e-03 5.8854235e-05 3.7442178e-02 1.5108135e-03 3.7442006e-02
 9.6255821e-01 9.9848914e-01 9.9994111e-01 9.9999774e-01 9.6255797e-01
 9.9848914e-01 9.9994111e-01 9.6255785e-01 9.9848914e-01 9.6255761e-01]


In [31]:
# p - train_y.numpy()

In [37]:
clf = LogisticRegression(random_state=41).fit(train_x, train_y)

clf.predict(test_x)
# clf.score(train_x, train_y)


array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])