In [1]:
import numpy as np
import torch as T
device = 'cpu'

In [2]:
seed = 0xEDA

In [42]:
print("Создадим данные")
T.manual_seed(seed)
np.random.seed(seed)

# 1. Модельные данные для обучения
# train_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5], [1.0, 2.0], [2.5, 7.5], [3.0, 9.0], [4.5, 11.5], [2.0, 6.0],
#     [4.5, 1.5], [5.5, 3.5], [7.5, 5.5], [4.5, 2.5], [8.0, 2.5], [6.5, 3.5], [8.5, 4.5], [5.0, 2.0]], 
#     dtype=np.float32)
# train_y = np.array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.compat.long)

# train_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5], [1.0, 2.0], [2.5, 7.5],
#     [4.5, 1.5], [6.5, 2.5], [8.5, 2.5], [4.5, 2.5], [8.0, 2.5]], dtype=np.float32)
# train_y = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=np.compat.long)

# train_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5],
#     [4.5, 1.5], [5.5, 3.5], [7.5, 5.5]], dtype=np.float32)
# train_y = np.array([1, 1, 1, 0, 0, 0], dtype=np.compat.long)


train_x = np.array([
    [1, 2], [1, 3], [1, 4], [1, 5], [2, 3], [2, 4], [2, 5], [3, 4], [3, 5], [4, 5],
    [2, 1], [3, 1], [4, 1], [5, 1], [3, 2], [4, 2], [5, 2], [4, 3], [5, 3], [5, 4]], dtype=np.float32)
train_y = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.compat.long)


# 2. Тестируемые данные
test_x = np.array([
    [1.5, 2.5], [3.5, 4.5], [6.5, 6.5],
    [4.5, 1.5], [5.5, 3.5], [7.5, 5.5]], dtype=np.float32)
test_y = np.array([1, 1, 1, 0, 0, 0], dtype=np.compat.long)

Создадим данные


In [43]:
print("Превратим в тензоры:")
print(train_x)
print(train_y)

train_x = T.tensor(train_x, dtype=T.float32).to(device)
train_y = T.tensor(train_y, dtype=T.long).to(device)

test_x = T.tensor(test_x, dtype=T.float32).to(device)
test_y = T.tensor(test_y, dtype=T.long).to(device)

# print(type(train_x))

Превратим в тензоры:
[[1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [3. 4.]
 [3. 5.]
 [4. 5.]
 [2. 1.]
 [3. 1.]
 [4. 1.]
 [5. 1.]
 [3. 2.]
 [4. 2.]
 [5. 2.]
 [4. 3.]
 [5. 3.]
 [5. 4.]]
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]


In [44]:
from sklearn.linear_model import LogisticRegression
from lr import LogisticRegression

In [45]:
my_lr = LogisticRegression(device)

lrn_rate = 0.05
indices = np.arange(6)

w, b = my_lr.fit(
    train_x,
    train_y,
    lrn_rate,
    indices,
    1000,
    0)

print(my_lr.w, my_lr.b)

tensor([0.5591, 1.2778], grad_fn=<AddBackward0>) tensor([0.4873], requires_grad=True)


In [48]:
p = my_lr.predict(train_x)

In [49]:
print(p)

[0.97345304 0.9924581  0.99788684 0.9994103  0.9956742  0.9987908
 0.99966276 0.99930835 0.9998072  0.99988973 0.94701374 0.9690036
 0.9820404  0.9896527  0.991165   0.99492973 0.997095   0.998582
 0.9991887  0.9997738 ]


In [40]:
p - train_y.numpy()

array([-0.02495271, -0.01226807, -0.06722677,  0.00133046,  0.031776  ,
        0.0633378 ])