In [1]:
import numpy as np
import torch as T
device = 'cpu'

In [2]:
seed = 0xEDA

In [3]:
print("Создадим данные")
T.manual_seed(seed)
np.random.seed(seed)

# 1. Модельные данные для обучения
# train_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5], [1.0, 2.0], [2.5, 7.5], [3.0, 9.0], [4.5, 11.5], [2.0, 6.0],
#     [4.5, 1.5], [5.5, 3.5], [7.5, 5.5], [4.5, 2.5], [8.0, 2.5], [6.5, 3.5], [8.5, 4.5], [5.0, 2.0]], 
#     dtype=np.float32)
# train_y = np.array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.compat.long)

# train_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5], [1.0, 2.0], [2.5, 7.5],
#     [4.5, 1.5], [6.5, 2.5], [8.5, 2.5], [4.5, 2.5], [8.0, 2.5]], dtype=np.float32)
# train_y = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=np.compat.long)

# train_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5],
#     [4.5, 1.5], [5.5, 3.5], [7.5, 5.5]], dtype=np.float32)
# train_y = np.array([1, 1, 1, 0, 0, 0], dtype=np.compat.long)


train_x = np.array([
    [1, 2], [1, 3], [1, 4], [1, 5], [2, 3], [2, 4], [2, 5], [3, 4], [3, 5], [4, 5],
    [2, 1], [3, 1], [4, 1], [5, 1], [3, 2], [4, 2], [5, 2], [4, 3], [5, 3], [5, 4]], dtype=np.float32)
train_y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=np.compat.long)


# 2. Тестируемые данные
test_x = np.copy(train_x)
test_y = np.copy(train_y)
# test_x = np.array([
#     [1.5, 2.5], [3.5, 4.5], [6.5, 6.5],
#     [4.5, 1.5], [5.5, 3.5], [7.5, 5.5]], dtype=np.float32)
# test_y = np.array([1, 1, 1, 0, 0, 0], dtype=np.compat.long)

Создадим данные


In [4]:
print("Превратим в тензоры:")
# print(train_x)
# print(train_y)

train_x = T.tensor(train_x, dtype=T.float32).to(device)
train_y = T.tensor(train_y, dtype=T.long).to(device)

test_x = T.tensor(test_x, dtype=T.float32).to(device)
test_y = T.tensor(test_y, dtype=T.long).to(device)


# train_x.size()
train_y.size()
# print(type(train_x))

Превратим в тензоры:


torch.Size([20])

In [5]:
from sklearn.linear_model import LogisticRegression
from lr import MyLogisticRegression

In [6]:
my_lr = MyLogisticRegression(device)

lrn_rate = 0.05
indices = np.arange(len(test_x))

w, b = my_lr.fit(
    train_x,
    train_y,
    lrn_rate,
    indices,
    1000,
    0)

print(my_lr.w, my_lr.b)

tensor([4., 2.]) tensor([-0.0059, -0.0073], grad_fn=<AddBackward0>) tensor([0.], requires_grad=True)
tensor([1., 4.]) tensor([-0.0059, -0.0073], grad_fn=<AddBackward0>) tensor([0.], requires_grad=True)
tensor([4., 3.]) tensor([-0.0059, -0.0073], grad_fn=<AddBackward0>) tensor([0.], requires_grad=True)
tensor([1., 3.]) tensor([-0.0059, -0.0073], grad_fn=<AddBackward0>) tensor([0.], requires_grad=True)
tensor([1., 5.]) tensor([-0.0059, -0.0073], grad_fn=<AddBackward0>) tensor([0.], requires_grad=True)
tensor([5., 3.]) tensor([-0.0059, -0.0073], grad_fn=<AddBackward0>) tensor([0.], requires_grad=True)
tensor([2., 1.]) tensor([-0.0059, -0.0073], grad_fn=<AddBackward0>) tensor([0.], requires_grad=True)
tensor([5., 1.]) tensor([-0.0059, -0.0073], grad_fn=<AddBackward0>) tensor([0.], requires_grad=True)
tensor([2., 5.]) tensor([-0.0059, -0.0073], grad_fn=<AddBackward0>) tensor([0.], requires_grad=True)
tensor([5., 4.]) tensor([-0.0059, -0.0073], grad_fn=<AddBackward0>) tensor([0.], requires_g

tensor([1., 2.]) tensor([ 0.9633, -0.9522], grad_fn=<AddBackward0>) tensor([0.0035], requires_grad=True)
tensor([5., 4.]) tensor([ 0.9633, -0.9522], grad_fn=<AddBackward0>) tensor([0.0035], requires_grad=True)
tensor([1., 3.]) tensor([ 0.9633, -0.9522], grad_fn=<AddBackward0>) tensor([0.0035], requires_grad=True)
tensor([4., 3.]) tensor([ 0.9633, -0.9522], grad_fn=<AddBackward0>) tensor([0.0035], requires_grad=True)
tensor([2., 3.]) tensor([ 0.9633, -0.9522], grad_fn=<AddBackward0>) tensor([0.0035], requires_grad=True)
tensor([5., 2.]) tensor([ 0.9633, -0.9522], grad_fn=<AddBackward0>) tensor([0.0035], requires_grad=True)
tensor([3., 2.]) tensor([ 0.9633, -0.9522], grad_fn=<AddBackward0>) tensor([0.0035], requires_grad=True)
tensor([1., 5.]) tensor([ 0.9633, -0.9522], grad_fn=<AddBackward0>) tensor([0.0035], requires_grad=True)
tensor([2., 5.]) tensor([ 0.9876, -0.9932], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 5.]) tensor([ 0.9876, -0.9932], grad_fn=<Ad

tensor([1., 5.]) tensor([ 1.3104, -1.3109], grad_fn=<AddBackward0>) tensor([0.0016], requires_grad=True)
tensor([4., 2.]) tensor([ 1.3104, -1.3109], grad_fn=<AddBackward0>) tensor([0.0016], requires_grad=True)
tensor([2., 3.]) tensor([ 1.3104, -1.3109], grad_fn=<AddBackward0>) tensor([0.0016], requires_grad=True)
tensor([4., 3.]) tensor([ 1.3274, -1.3279], grad_fn=<AddBackward0>) tensor([0.0016], requires_grad=True)
tensor([1., 5.]) tensor([ 1.3274, -1.3279], grad_fn=<AddBackward0>) tensor([0.0016], requires_grad=True)
tensor([4., 2.]) tensor([ 1.3274, -1.3279], grad_fn=<AddBackward0>) tensor([0.0016], requires_grad=True)
tensor([3., 5.]) tensor([ 1.3274, -1.3279], grad_fn=<AddBackward0>) tensor([0.0016], requires_grad=True)
tensor([1., 3.]) tensor([ 1.3274, -1.3279], grad_fn=<AddBackward0>) tensor([0.0016], requires_grad=True)
tensor([2., 5.]) tensor([ 1.3274, -1.3279], grad_fn=<AddBackward0>) tensor([0.0016], requires_grad=True)
tensor([3., 1.]) tensor([ 1.3274, -1.3279], grad_fn=<Ad

tensor([5., 2.]) tensor([ 1.5355, -1.5359], grad_fn=<AddBackward0>) tensor([0.0015], requires_grad=True)
tensor([1., 3.]) tensor([ 1.5355, -1.5359], grad_fn=<AddBackward0>) tensor([0.0015], requires_grad=True)
tensor([5., 1.]) tensor([ 1.5355, -1.5359], grad_fn=<AddBackward0>) tensor([0.0015], requires_grad=True)
tensor([5., 4.]) tensor([ 1.5355, -1.5359], grad_fn=<AddBackward0>) tensor([0.0015], requires_grad=True)
tensor([2., 4.]) tensor([ 1.5355, -1.5359], grad_fn=<AddBackward0>) tensor([0.0015], requires_grad=True)
tensor([1., 2.]) tensor([ 1.5355, -1.5359], grad_fn=<AddBackward0>) tensor([0.0015], requires_grad=True)
tensor([4., 5.]) tensor([ 1.5355, -1.5359], grad_fn=<AddBackward0>) tensor([0.0015], requires_grad=True)
tensor([2., 5.]) tensor([ 1.5355, -1.5359], grad_fn=<AddBackward0>) tensor([0.0015], requires_grad=True)
tensor([4., 2.]) tensor([ 1.5355, -1.5359], grad_fn=<AddBackward0>) tensor([0.0015], requires_grad=True)
tensor([5., 3.]) tensor([ 1.5355, -1.5359], grad_fn=<Ad

tensor([2., 1.]) tensor([ 1.6880, -1.6884], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([5., 3.]) tensor([ 1.6880, -1.6884], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([3., 1.]) tensor([ 1.6880, -1.6884], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([4., 1.]) tensor([ 1.6880, -1.6884], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([3., 4.]) tensor([ 1.6880, -1.6884], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([5., 1.]) tensor([ 1.6969, -1.6973], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([2., 3.]) tensor([ 1.6969, -1.6973], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([1., 3.]) tensor([ 1.6969, -1.6973], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([3., 4.]) tensor([ 1.6969, -1.6973], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([3., 1.]) tensor([ 1.6969, -1.6973], grad_fn=<Ad

tensor([4., 1.]) tensor([ 1.8159, -1.8163], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([5., 3.]) tensor([ 1.8159, -1.8163], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([4., 5.]) tensor([ 1.8159, -1.8163], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([2., 3.]) tensor([ 1.8159, -1.8163], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([2., 5.]) tensor([ 1.8159, -1.8163], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([1., 2.]) tensor([ 1.8159, -1.8163], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([2., 1.]) tensor([ 1.8159, -1.8163], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([5., 1.]) tensor([ 1.8159, -1.8163], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([4., 3.]) tensor([ 1.8159, -1.8163], grad_fn=<AddBackward0>) tensor([0.0014], requires_grad=True)
tensor([5., 4.]) tensor([ 1.8159, -1.8163], grad_fn=<Ad

tensor([1., 3.]) tensor([ 1.9207, -1.9211], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([4., 1.]) tensor([ 1.9207, -1.9211], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([1., 4.]) tensor([ 1.9207, -1.9211], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([4., 2.]) tensor([ 1.9207, -1.9211], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([1., 5.]) tensor([ 1.9207, -1.9211], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([5., 2.]) tensor([ 1.9207, -1.9211], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([5., 1.]) tensor([ 1.9207, -1.9211], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([3., 4.]) tensor([ 1.9207, -1.9211], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([2., 4.]) tensor([ 1.9207, -1.9211], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([4., 5.]) tensor([ 1.9207, -1.9211], grad_fn=<Ad

tensor([2., 4.]) tensor([ 2.0094, -2.0098], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([5., 4.]) tensor([ 2.0094, -2.0098], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([4., 1.]) tensor([ 2.0094, -2.0098], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([4., 3.]) tensor([ 2.0094, -2.0098], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([2., 5.]) tensor([ 2.0094, -2.0098], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([1., 5.]) tensor([ 2.0094, -2.0098], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([5., 1.]) tensor([ 2.0094, -2.0098], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([5., 3.]) tensor([ 2.0094, -2.0098], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([2., 3.]) tensor([ 2.0094, -2.0098], grad_fn=<AddBackward0>) tensor([0.0013], requires_grad=True)
tensor([5., 2.]) tensor([ 2.0094, -2.0098], grad_fn=<Ad

tensor([4., 1.]) tensor([ 2.0863, -2.0866], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([2., 1.]) tensor([ 2.0863, -2.0866], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([4., 2.]) tensor([ 2.0863, -2.0866], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([4., 5.]) tensor([ 2.0863, -2.0866], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([5., 1.]) tensor([ 2.0863, -2.0866], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([2., 5.]) tensor([ 2.0863, -2.0866], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([5., 3.]) tensor([ 2.0863, -2.0866], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([1., 2.]) tensor([ 2.0863, -2.0866], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([3., 1.]) tensor([ 2.0863, -2.0866], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([3., 5.]) tensor([ 2.0863, -2.0866], grad_fn=<Ad

tensor([2., 1.]) tensor([ 2.1540, -2.1544], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([5., 1.]) tensor([ 2.1540, -2.1544], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([4., 5.]) tensor([ 2.1540, -2.1544], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([2., 3.]) tensor([ 2.1540, -2.1544], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([2., 5.]) tensor([ 2.1540, -2.1544], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([3., 2.]) tensor([ 2.1540, -2.1544], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([5., 4.]) tensor([ 2.1540, -2.1544], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([4., 2.]) tensor([ 2.1540, -2.1544], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([1., 5.]) tensor([ 2.1540, -2.1544], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([3., 1.]) tensor([ 2.1540, -2.1544], grad_fn=<Ad

tensor([5., 1.]) tensor([ 2.2109, -2.2113], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([4., 2.]) tensor([ 2.2109, -2.2113], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([2., 5.]) tensor([ 2.2109, -2.2113], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([4., 3.]) tensor([ 2.2109, -2.2113], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([3., 1.]) tensor([ 2.2109, -2.2113], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([2., 4.]) tensor([ 2.2109, -2.2113], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([1., 2.]) tensor([ 2.2109, -2.2113], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([4., 1.]) tensor([ 2.2109, -2.2113], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([5., 3.]) tensor([ 2.2145, -2.2149], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([5., 1.]) tensor([ 2.2145, -2.2149], grad_fn=<Ad

tensor([1., 3.]) tensor([ 2.2660, -2.2663], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([3., 4.]) tensor([ 2.2660, -2.2663], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([1., 5.]) tensor([ 2.2660, -2.2663], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([5., 1.]) tensor([ 2.2660, -2.2663], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([2., 3.]) tensor([ 2.2660, -2.2663], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([1., 2.]) tensor([ 2.2660, -2.2663], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([2., 1.]) tensor([ 2.2660, -2.2663], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([3., 5.]) tensor([ 2.2660, -2.2663], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([2., 5.]) tensor([ 2.2660, -2.2663], grad_fn=<AddBackward0>) tensor([0.0012], requires_grad=True)
tensor([4., 3.]) tensor([ 2.2660, -2.2663], grad_fn=<Ad

tensor([4., 5.]) tensor([ 2.3131, -2.3134], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([2., 4.]) tensor([ 2.3131, -2.3134], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([2., 5.]) tensor([ 2.3161, -2.3165], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([3., 2.]) tensor([ 2.3161, -2.3165], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([5., 1.]) tensor([ 2.3161, -2.3165], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([5., 4.]) tensor([ 2.3161, -2.3165], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([1., 3.]) tensor([ 2.3161, -2.3165], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([1., 4.]) tensor([ 2.3161, -2.3165], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([1., 2.]) tensor([ 2.3161, -2.3165], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 3.]) tensor([ 2.3161, -2.3165], grad_fn=<Ad

tensor([2., 4.]) tensor([ 2.3594, -2.3597], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([3., 2.]) tensor([ 2.3594, -2.3597], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([3., 4.]) tensor([ 2.3594, -2.3597], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 2.]) tensor([ 2.3594, -2.3597], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([1., 3.]) tensor([ 2.3594, -2.3597], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([3., 1.]) tensor([ 2.3594, -2.3597], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([1., 2.]) tensor([ 2.3594, -2.3597], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([2., 1.]) tensor([ 2.3594, -2.3597], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 5.]) tensor([ 2.3594, -2.3597], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([5., 4.]) tensor([ 2.3594, -2.3597], grad_fn=<Ad

tensor([3., 5.]) tensor([ 2.4021, -2.4025], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([3., 2.]) tensor([ 2.4021, -2.4025], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([1., 5.]) tensor([ 2.4021, -2.4025], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 3.]) tensor([ 2.4021, -2.4025], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([5., 4.]) tensor([ 2.4021, -2.4025], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([1., 4.]) tensor([ 2.4021, -2.4025], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 2.]) tensor([ 2.4021, -2.4025], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([5., 2.]) tensor([ 2.4021, -2.4025], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 5.]) tensor([ 2.4021, -2.4025], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([2., 1.]) tensor([ 2.4021, -2.4025], grad_fn=<Ad

tensor([1., 3.]) tensor([ 2.4419, -2.4422], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([1., 2.]) tensor([ 2.4419, -2.4422], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 3.]) tensor([ 2.4419, -2.4422], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([2., 3.]) tensor([ 2.4419, -2.4422], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([1., 5.]) tensor([ 2.4419, -2.4422], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([3., 2.]) tensor([ 2.4419, -2.4422], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 2.]) tensor([ 2.4419, -2.4422], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([3., 1.]) tensor([ 2.4419, -2.4422], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([3., 5.]) tensor([ 2.4419, -2.4422], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([5., 2.]) tensor([ 2.4419, -2.4422], grad_fn=<Ad

tensor([5., 4.]) tensor([ 2.4767, -2.4770], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 2.]) tensor([ 2.4767, -2.4770], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 5.]) tensor([ 2.4789, -2.4792], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([3., 2.]) tensor([ 2.4789, -2.4792], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([4., 1.]) tensor([ 2.4789, -2.4792], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([5., 3.]) tensor([ 2.4789, -2.4792], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([2., 1.]) tensor([ 2.4789, -2.4792], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([2., 3.]) tensor([ 2.4789, -2.4792], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([3., 4.]) tensor([ 2.4789, -2.4792], grad_fn=<AddBackward0>) tensor([0.0011], requires_grad=True)
tensor([1., 2.]) tensor([ 2.4789, -2.4792], grad_fn=<Ad

tensor([2., 3.]) tensor([ 2.5116, -2.5119], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 2.]) tensor([ 2.5116, -2.5119], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 3.]) tensor([ 2.5116, -2.5119], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 2.]) tensor([ 2.5116, -2.5119], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 4.]) tensor([ 2.5116, -2.5119], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 3.]) tensor([ 2.5137, -2.5140], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 2.]) tensor([ 2.5137, -2.5140], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([5., 3.]) tensor([ 2.5137, -2.5140], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 4.]) tensor([ 2.5137, -2.5140], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 3.]) tensor([ 2.5137, -2.5140], grad_fn=<Ad

tensor([5., 2.]) tensor([ 2.5444, -2.5447], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([5., 1.]) tensor([ 2.5444, -2.5447], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 4.]) tensor([ 2.5444, -2.5447], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 2.]) tensor([ 2.5444, -2.5447], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 4.]) tensor([ 2.5444, -2.5447], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 4.]) tensor([ 2.5444, -2.5447], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 2.]) tensor([ 2.5444, -2.5447], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 5.]) tensor([ 2.5444, -2.5447], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 5.]) tensor([ 2.5444, -2.5447], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 3.]) tensor([ 2.5444, -2.5447], grad_fn=<Ad

tensor([5., 4.]) tensor([ 2.5754, -2.5757], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 1.]) tensor([ 2.5754, -2.5757], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 3.]) tensor([ 2.5754, -2.5757], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([5., 1.]) tensor([ 2.5754, -2.5757], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 4.]) tensor([ 2.5754, -2.5757], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([5., 2.]) tensor([ 2.5754, -2.5757], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 4.]) tensor([ 2.5754, -2.5757], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 5.]) tensor([ 2.5754, -2.5757], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 2.]) tensor([ 2.5754, -2.5757], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 1.]) tensor([ 2.5754, -2.5757], grad_fn=<Ad

tensor([5., 4.]) tensor([ 2.6047, -2.6050], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 4.]) tensor([ 2.6047, -2.6050], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 5.]) tensor([ 2.6047, -2.6050], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 1.]) tensor([ 2.6047, -2.6050], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 3.]) tensor([ 2.6047, -2.6050], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 2.]) tensor([ 2.6047, -2.6050], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 5.]) tensor([ 2.6047, -2.6050], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 3.]) tensor([ 2.6047, -2.6050], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 2.]) tensor([ 2.6047, -2.6050], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 4.]) tensor([ 2.6047, -2.6050], grad_fn=<Ad

tensor([2., 4.]) tensor([ 2.6325, -2.6328], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([5., 2.]) tensor([ 2.6325, -2.6328], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 2.]) tensor([ 2.6325, -2.6328], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 4.]) tensor([ 2.6325, -2.6328], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([5., 4.]) tensor([ 2.6325, -2.6328], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 2.]) tensor([ 2.6325, -2.6328], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 5.]) tensor([ 2.6325, -2.6328], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 5.]) tensor([ 2.6325, -2.6328], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([5., 3.]) tensor([ 2.6325, -2.6328], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 3.]) tensor([ 2.6325, -2.6328], grad_fn=<Ad

tensor([1., 3.]) tensor([ 2.6590, -2.6593], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 2.]) tensor([ 2.6590, -2.6593], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([5., 2.]) tensor([ 2.6590, -2.6593], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 2.]) tensor([ 2.6590, -2.6593], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 5.]) tensor([ 2.6590, -2.6593], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 1.]) tensor([ 2.6590, -2.6593], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 4.]) tensor([ 2.6590, -2.6593], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 1.]) tensor([ 2.6590, -2.6593], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 5.]) tensor([ 2.6590, -2.6593], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 2.]) tensor([ 2.6590, -2.6593], grad_fn=<Ad

tensor([4., 3.]) tensor([ 2.6828, -2.6831], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 5.]) tensor([ 2.6828, -2.6831], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 5.]) tensor([ 2.6828, -2.6831], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 2.]) tensor([ 2.6828, -2.6831], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 4.]) tensor([ 2.6828, -2.6831], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 2.]) tensor([ 2.6828, -2.6831], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 5.]) tensor([ 2.6843, -2.6846], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 4.]) tensor([ 2.6843, -2.6846], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 4.]) tensor([ 2.6843, -2.6846], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 4.]) tensor([ 2.6843, -2.6846], grad_fn=<Ad

tensor([5., 2.]) tensor([ 2.7070, -2.7073], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 5.]) tensor([ 2.7070, -2.7073], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 4.]) tensor([ 2.7070, -2.7073], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 5.]) tensor([ 2.7070, -2.7073], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 2.]) tensor([ 2.7070, -2.7073], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 2.]) tensor([ 2.7070, -2.7073], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 1.]) tensor([ 2.7070, -2.7073], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 3.]) tensor([ 2.7070, -2.7073], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 1.]) tensor([ 2.7085, -2.7088], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 3.]) tensor([ 2.7085, -2.7088], grad_fn=<Ad

tensor([2., 3.]) tensor([ 2.7302, -2.7305], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 4.]) tensor([ 2.7302, -2.7305], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 2.]) tensor([ 2.7302, -2.7305], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 1.]) tensor([ 2.7302, -2.7305], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([5., 2.]) tensor([ 2.7302, -2.7305], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([1., 2.]) tensor([ 2.7302, -2.7305], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([2., 5.]) tensor([ 2.7302, -2.7305], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([5., 3.]) tensor([ 2.7302, -2.7305], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([4., 2.]) tensor([ 2.7302, -2.7305], grad_fn=<AddBackward0>) tensor([0.0010], requires_grad=True)
tensor([3., 4.]) tensor([ 2.7302, -2.7305], grad_fn=<Ad

tensor([1., 3.]) tensor([ 2.7524, -2.7527], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 3.]) tensor([ 2.7524, -2.7527], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 2.]) tensor([ 2.7524, -2.7527], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 5.]) tensor([ 2.7524, -2.7527], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 4.]) tensor([ 2.7524, -2.7527], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 5.]) tensor([ 2.7524, -2.7527], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 3.]) tensor([ 2.7524, -2.7527], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 2.7524, -2.7527], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 2.]) tensor([ 2.7524, -2.7527], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 2.]) tensor([ 2.7524, -2.7527], grad_fn=<Ad

tensor([1., 5.]) tensor([ 2.7725, -2.7728], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 2.]) tensor([ 2.7725, -2.7728], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 3.]) tensor([ 2.7725, -2.7728], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 4.]) tensor([ 2.7725, -2.7728], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 2.]) tensor([ 2.7725, -2.7728], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 1.]) tensor([ 2.7725, -2.7728], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 5.]) tensor([ 2.7725, -2.7728], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 2.]) tensor([ 2.7738, -2.7741], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 2.7738, -2.7741], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 4.]) tensor([ 2.7738, -2.7741], grad_fn=<Ad

tensor([4., 1.]) tensor([ 2.7931, -2.7934], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 2.]) tensor([ 2.7931, -2.7934], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 1.]) tensor([ 2.7931, -2.7934], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 5.]) tensor([ 2.7931, -2.7934], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 1.]) tensor([ 2.7931, -2.7934], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 3.]) tensor([ 2.7931, -2.7934], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 1.]) tensor([ 2.7931, -2.7934], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 4.]) tensor([ 2.7931, -2.7934], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 5.]) tensor([ 2.7931, -2.7934], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 4.]) tensor([ 2.7931, -2.7934], grad_fn=<Ad

tensor([2., 3.]) tensor([ 2.8118, -2.8120], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 1.]) tensor([ 2.8118, -2.8120], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 4.]) tensor([ 2.8118, -2.8120], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 3.]) tensor([ 2.8118, -2.8120], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 1.]) tensor([ 2.8118, -2.8120], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 2.]) tensor([ 2.8118, -2.8120], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 4.]) tensor([ 2.8118, -2.8120], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 2.]) tensor([ 2.8130, -2.8133], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 2.8130, -2.8133], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 2.]) tensor([ 2.8130, -2.8133], grad_fn=<Ad

tensor([2., 1.]) tensor([ 2.8310, -2.8312], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 1.]) tensor([ 2.8310, -2.8312], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 3.]) tensor([ 2.8310, -2.8312], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 5.]) tensor([ 2.8310, -2.8312], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 4.]) tensor([ 2.8310, -2.8312], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 4.]) tensor([ 2.8310, -2.8312], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 4.]) tensor([ 2.8310, -2.8312], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 2.]) tensor([ 2.8310, -2.8312], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 3.]) tensor([ 2.8310, -2.8312], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 2.]) tensor([ 2.8310, -2.8312], grad_fn=<Ad

tensor([5., 2.]) tensor([ 2.8495, -2.8498], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 5.]) tensor([ 2.8495, -2.8498], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 1.]) tensor([ 2.8495, -2.8498], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 4.]) tensor([ 2.8495, -2.8498], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 5.]) tensor([ 2.8495, -2.8498], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 4.]) tensor([ 2.8495, -2.8498], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 2.8495, -2.8498], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 2.]) tensor([ 2.8495, -2.8498], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 4.]) tensor([ 2.8495, -2.8498], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 1.]) tensor([ 2.8495, -2.8498], grad_fn=<Ad

tensor([4., 5.]) tensor([ 2.8663, -2.8666], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 3.]) tensor([ 2.8663, -2.8666], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 4.]) tensor([ 2.8663, -2.8666], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 3.]) tensor([ 2.8663, -2.8666], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 5.]) tensor([ 2.8663, -2.8666], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 4.]) tensor([ 2.8674, -2.8677], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 4.]) tensor([ 2.8674, -2.8677], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 2.8674, -2.8677], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 3.]) tensor([ 2.8674, -2.8677], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 4.]) tensor([ 2.8674, -2.8677], grad_fn=<Ad

tensor([3., 2.]) tensor([ 2.8837, -2.8840], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 3.]) tensor([ 2.8837, -2.8840], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 3.]) tensor([ 2.8837, -2.8840], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 2.]) tensor([ 2.8837, -2.8840], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 2.]) tensor([ 2.8837, -2.8840], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 5.]) tensor([ 2.8837, -2.8840], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 5.]) tensor([ 2.8837, -2.8840], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 1.]) tensor([ 2.8837, -2.8840], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 2.]) tensor([ 2.8837, -2.8840], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 1.]) tensor([ 2.8837, -2.8840], grad_fn=<Ad

tensor([4., 1.]) tensor([ 2.8995, -2.8998], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 3.]) tensor([ 2.8995, -2.8998], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 4.]) tensor([ 2.9006, -2.9008], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 2.]) tensor([ 2.9006, -2.9008], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 1.]) tensor([ 2.9006, -2.9008], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 4.]) tensor([ 2.9006, -2.9008], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 3.]) tensor([ 2.9006, -2.9008], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 5.]) tensor([ 2.9006, -2.9008], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 5.]) tensor([ 2.9006, -2.9008], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 3.]) tensor([ 2.9006, -2.9008], grad_fn=<Ad

tensor([2., 4.]) tensor([ 2.9159, -2.9162], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 2.]) tensor([ 2.9159, -2.9162], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 5.]) tensor([ 2.9159, -2.9162], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 2.]) tensor([ 2.9159, -2.9162], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 2.]) tensor([ 2.9159, -2.9162], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 5.]) tensor([ 2.9159, -2.9162], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 4.]) tensor([ 2.9159, -2.9162], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 2.]) tensor([ 2.9159, -2.9162], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 4.]) tensor([ 2.9169, -2.9172], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 5.]) tensor([ 2.9169, -2.9172], grad_fn=<Ad

tensor([5., 1.]) tensor([ 2.9318, -2.9320], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 4.]) tensor([ 2.9318, -2.9320], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 2.9318, -2.9320], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 3.]) tensor([ 2.9318, -2.9320], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 3.]) tensor([ 2.9318, -2.9320], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 2.]) tensor([ 2.9318, -2.9320], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 4.]) tensor([ 2.9318, -2.9320], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 5.]) tensor([ 2.9318, -2.9320], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 3.]) tensor([ 2.9318, -2.9320], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 4.]) tensor([ 2.9328, -2.9330], grad_fn=<Ad

tensor([1., 3.]) tensor([ 2.9472, -2.9475], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 2.9472, -2.9475], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 1.]) tensor([ 2.9482, -2.9484], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 1.]) tensor([ 2.9482, -2.9484], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 4.]) tensor([ 2.9482, -2.9484], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 1.]) tensor([ 2.9482, -2.9484], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 5.]) tensor([ 2.9482, -2.9484], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 5.]) tensor([ 2.9482, -2.9484], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 4.]) tensor([ 2.9482, -2.9484], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 4.]) tensor([ 2.9482, -2.9484], grad_fn=<Ad

tensor([2., 1.]) tensor([ 2.9622, -2.9625], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 5.]) tensor([ 2.9622, -2.9625], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 5.]) tensor([ 2.9622, -2.9625], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 2.]) tensor([ 2.9622, -2.9625], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 2.9622, -2.9625], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 2.]) tensor([ 2.9622, -2.9625], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 1.]) tensor([ 2.9622, -2.9625], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 4.]) tensor([ 2.9622, -2.9625], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 3.]) tensor([ 2.9622, -2.9625], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 2.]) tensor([ 2.9622, -2.9625], grad_fn=<Ad

tensor([1., 4.]) tensor([ 2.9768, -2.9770], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 3.]) tensor([ 2.9768, -2.9770], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 2.9768, -2.9770], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 3.]) tensor([ 2.9768, -2.9770], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 5.]) tensor([ 2.9768, -2.9770], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 5.]) tensor([ 2.9768, -2.9770], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 2.]) tensor([ 2.9768, -2.9770], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 5.]) tensor([ 2.9768, -2.9770], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 3.]) tensor([ 2.9768, -2.9770], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 1.]) tensor([ 2.9768, -2.9770], grad_fn=<Ad

tensor([3., 4.]) tensor([ 2.9910, -2.9912], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 5.]) tensor([ 2.9910, -2.9912], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 2.9910, -2.9912], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 3.]) tensor([ 2.9910, -2.9912], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 2.]) tensor([ 2.9910, -2.9912], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 4.]) tensor([ 2.9910, -2.9912], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 1.]) tensor([ 2.9910, -2.9912], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 4.]) tensor([ 2.9910, -2.9912], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 2.]) tensor([ 2.9910, -2.9912], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 5.]) tensor([ 2.9910, -2.9912], grad_fn=<Ad

tensor([4., 2.]) tensor([ 3.0040, -3.0042], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 3.]) tensor([ 3.0040, -3.0042], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 1.]) tensor([ 3.0040, -3.0042], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 2.]) tensor([ 3.0040, -3.0042], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([4., 3.]) tensor([ 3.0040, -3.0042], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 3.]) tensor([ 3.0040, -3.0042], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([3., 2.]) tensor([ 3.0040, -3.0042], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([2., 4.]) tensor([ 3.0048, -3.0051], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([5., 1.]) tensor([ 3.0048, -3.0051], grad_fn=<AddBackward0>) tensor([0.0009], requires_grad=True)
tensor([1., 3.]) tensor([ 3.0048, -3.0051], grad_fn=<Ad

tensor([4., 5.]) tensor([ 3.0175, -3.0177], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 1.]) tensor([ 3.0175, -3.0177], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 4.]) tensor([ 3.0175, -3.0177], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.0175, -3.0177], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.0175, -3.0177], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.0175, -3.0177], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.0175, -3.0177], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 4.]) tensor([ 3.0175, -3.0177], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 2.]) tensor([ 3.0175, -3.0177], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.0175, -3.0177], grad_fn=<Ad

tensor([1., 4.]) tensor([ 3.0298, -3.0301], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.0298, -3.0301], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.0298, -3.0301], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.0298, -3.0301], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 1.]) tensor([ 3.0298, -3.0301], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.0298, -3.0301], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.0298, -3.0301], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.0306, -3.0309], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.0306, -3.0309], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 3.]) tensor([ 3.0306, -3.0309], grad_fn=<Ad

tensor([4., 3.]) tensor([ 3.0427, -3.0429], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 1.]) tensor([ 3.0427, -3.0429], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.0427, -3.0429], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 3.]) tensor([ 3.0427, -3.0429], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.0427, -3.0429], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.0427, -3.0429], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.0427, -3.0429], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.0427, -3.0429], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.0435, -3.0437], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.0435, -3.0437], grad_fn=<Ad

tensor([3., 2.]) tensor([ 3.0553, -3.0555], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.0553, -3.0555], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.0553, -3.0555], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 4.]) tensor([ 3.0553, -3.0555], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 5.]) tensor([ 3.0553, -3.0555], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.0553, -3.0555], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 2.]) tensor([ 3.0553, -3.0555], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.0553, -3.0555], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 3.]) tensor([ 3.0553, -3.0555], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 3.]) tensor([ 3.0553, -3.0555], grad_fn=<Ad

tensor([1., 4.]) tensor([ 3.0683, -3.0686], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.0683, -3.0686], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.0683, -3.0686], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 3.]) tensor([ 3.0683, -3.0686], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.0683, -3.0686], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 1.]) tensor([ 3.0683, -3.0686], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.0683, -3.0686], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.0683, -3.0686], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.0683, -3.0686], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.0683, -3.0686], grad_fn=<Ad

tensor([1., 2.]) tensor([ 3.0803, -3.0805], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 3.]) tensor([ 3.0803, -3.0805], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 3.]) tensor([ 3.0803, -3.0805], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.0803, -3.0805], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 5.]) tensor([ 3.0803, -3.0805], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.0803, -3.0805], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 2.]) tensor([ 3.0803, -3.0805], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.0803, -3.0805], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.0803, -3.0805], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.0803, -3.0805], grad_fn=<Ad

tensor([4., 1.]) tensor([ 3.0913, -3.0915], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.0913, -3.0915], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 2.]) tensor([ 3.0913, -3.0915], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 4.]) tensor([ 3.0913, -3.0915], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 1.]) tensor([ 3.0913, -3.0915], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.0913, -3.0915], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.0920, -3.0923], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 1.]) tensor([ 3.0920, -3.0923], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 5.]) tensor([ 3.0920, -3.0923], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.0920, -3.0923], grad_fn=<Ad

tensor([1., 3.]) tensor([ 3.1028, -3.1030], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.1028, -3.1030], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 4.]) tensor([ 3.1028, -3.1030], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 2.]) tensor([ 3.1028, -3.1030], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 4.]) tensor([ 3.1028, -3.1030], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 1.]) tensor([ 3.1028, -3.1030], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 1.]) tensor([ 3.1028, -3.1030], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.1028, -3.1030], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.1028, -3.1030], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.1028, -3.1030], grad_fn=<Ad

tensor([5., 4.]) tensor([ 3.1140, -3.1143], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.1140, -3.1143], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.1140, -3.1143], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 1.]) tensor([ 3.1140, -3.1143], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 4.]) tensor([ 3.1140, -3.1143], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.1140, -3.1143], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 4.]) tensor([ 3.1140, -3.1143], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 5.]) tensor([ 3.1140, -3.1143], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 1.]) tensor([ 3.1140, -3.1143], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.1140, -3.1143], grad_fn=<Ad

tensor([2., 1.]) tensor([ 3.1251, -3.1253], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 4.]) tensor([ 3.1251, -3.1253], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 1.]) tensor([ 3.1251, -3.1253], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.1251, -3.1253], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 1.]) tensor([ 3.1251, -3.1253], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.1251, -3.1253], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.1251, -3.1253], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 3.]) tensor([ 3.1251, -3.1253], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.1251, -3.1253], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.1251, -3.1253], grad_fn=<Ad

tensor([4., 3.]) tensor([ 3.1352, -3.1354], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.1352, -3.1354], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.1358, -3.1361], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.1358, -3.1361], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 1.]) tensor([ 3.1358, -3.1361], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 4.]) tensor([ 3.1358, -3.1361], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.1358, -3.1361], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 3.]) tensor([ 3.1358, -3.1361], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.1358, -3.1361], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.1358, -3.1361], grad_fn=<Ad

tensor([3., 4.]) tensor([ 3.1458, -3.1460], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 2.]) tensor([ 3.1458, -3.1460], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 4.]) tensor([ 3.1458, -3.1460], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.1458, -3.1460], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 5.]) tensor([ 3.1458, -3.1460], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 1.]) tensor([ 3.1464, -3.1466], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 5.]) tensor([ 3.1464, -3.1466], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 4.]) tensor([ 3.1464, -3.1466], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.1464, -3.1466], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 2.]) tensor([ 3.1464, -3.1466], grad_fn=<Ad

tensor([2., 5.]) tensor([ 3.1561, -3.1564], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 2.]) tensor([ 3.1561, -3.1564], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.1561, -3.1564], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.1561, -3.1564], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 1.]) tensor([ 3.1561, -3.1564], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 2.]) tensor([ 3.1561, -3.1564], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.1561, -3.1564], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 4.]) tensor([ 3.1561, -3.1564], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 3.]) tensor([ 3.1561, -3.1564], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 4.]) tensor([ 3.1561, -3.1564], grad_fn=<Ad

tensor([3., 5.]) tensor([ 3.1657, -3.1659], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 4.]) tensor([ 3.1657, -3.1659], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 1.]) tensor([ 3.1657, -3.1659], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 1.]) tensor([ 3.1657, -3.1659], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.1657, -3.1659], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 2.]) tensor([ 3.1657, -3.1659], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.1657, -3.1659], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.1657, -3.1659], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 3.]) tensor([ 3.1663, -3.1666], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.1663, -3.1666], grad_fn=<Ad

tensor([4., 5.]) tensor([ 3.1751, -3.1753], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.1751, -3.1753], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.1757, -3.1759], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.1757, -3.1759], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 2.]) tensor([ 3.1757, -3.1759], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 4.]) tensor([ 3.1757, -3.1759], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 1.]) tensor([ 3.1757, -3.1759], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.1757, -3.1759], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 2.]) tensor([ 3.1757, -3.1759], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 4.]) tensor([ 3.1757, -3.1759], grad_fn=<Ad

tensor([2., 1.]) tensor([ 3.1849, -3.1851], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.1849, -3.1851], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.1849, -3.1851], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 1.]) tensor([ 3.1849, -3.1851], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.1849, -3.1851], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 4.]) tensor([ 3.1849, -3.1851], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 3.]) tensor([ 3.1849, -3.1851], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 2.]) tensor([ 3.1849, -3.1851], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.1849, -3.1851], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 2.]) tensor([ 3.1849, -3.1851], grad_fn=<Ad

tensor([5., 4.]) tensor([ 3.1945, -3.1948], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.1945, -3.1948], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.1945, -3.1948], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 4.]) tensor([ 3.1945, -3.1948], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.1945, -3.1948], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 1.]) tensor([ 3.1945, -3.1948], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.1945, -3.1948], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 4.]) tensor([ 3.1945, -3.1948], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.1945, -3.1948], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 5.]) tensor([ 3.1945, -3.1948], grad_fn=<Ad

tensor([4., 5.]) tensor([ 3.2034, -3.2037], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.2034, -3.2037], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.2034, -3.2037], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.2034, -3.2037], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 1.]) tensor([ 3.2034, -3.2037], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.2034, -3.2037], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.2034, -3.2037], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 4.]) tensor([ 3.2034, -3.2037], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.2034, -3.2037], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.2034, -3.2037], grad_fn=<Ad

tensor([4., 2.]) tensor([ 3.2122, -3.2124], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.2128, -3.2130], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 2.]) tensor([ 3.2128, -3.2130], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.2128, -3.2130], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 5.]) tensor([ 3.2128, -3.2130], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.2128, -3.2130], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 1.]) tensor([ 3.2128, -3.2130], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 1.]) tensor([ 3.2128, -3.2130], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.2128, -3.2130], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 3.]) tensor([ 3.2128, -3.2130], grad_fn=<Ad

tensor([5., 1.]) tensor([ 3.2213, -3.2216], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 3.]) tensor([ 3.2213, -3.2216], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 2.]) tensor([ 3.2219, -3.2221], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 1.]) tensor([ 3.2219, -3.2221], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 2.]) tensor([ 3.2219, -3.2221], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 3.]) tensor([ 3.2219, -3.2221], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 4.]) tensor([ 3.2219, -3.2221], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.2219, -3.2221], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 4.]) tensor([ 3.2219, -3.2221], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.2219, -3.2221], grad_fn=<Ad

tensor([3., 5.]) tensor([ 3.2304, -3.2306], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 4.]) tensor([ 3.2304, -3.2306], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 4.]) tensor([ 3.2304, -3.2306], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.2304, -3.2306], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 4.]) tensor([ 3.2309, -3.2311], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 3.]) tensor([ 3.2309, -3.2311], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 2.]) tensor([ 3.2309, -3.2311], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 2.]) tensor([ 3.2309, -3.2311], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 5.]) tensor([ 3.2309, -3.2311], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 3.]) tensor([ 3.2309, -3.2311], grad_fn=<Ad

tensor([1., 4.]) tensor([ 3.2392, -3.2394], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.2392, -3.2394], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 1.]) tensor([ 3.2392, -3.2394], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([5., 2.]) tensor([ 3.2392, -3.2394], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.2392, -3.2394], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 1.]) tensor([ 3.2392, -3.2394], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 3.]) tensor([ 3.2392, -3.2394], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 1.]) tensor([ 3.2392, -3.2394], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 4.]) tensor([ 3.2398, -3.2400], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 4.]) tensor([ 3.2398, -3.2400], grad_fn=<Ad

In [7]:
p = my_lr.predict(test_x)

tensor([1., 2.]) tensor([ 3.2469, -3.2471], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 3.]) tensor([ 3.2469, -3.2471], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 4.]) tensor([ 3.2469, -3.2471], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([1., 5.]) tensor([ 3.2469, -3.2471], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 3.]) tensor([ 3.2469, -3.2471], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 4.]) tensor([ 3.2469, -3.2471], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([2., 5.]) tensor([ 3.2469, -3.2471], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 4.]) tensor([ 3.2469, -3.2471], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([3., 5.]) tensor([ 3.2469, -3.2471], grad_fn=<AddBackward0>) tensor([0.0008], requires_grad=True)
tensor([4., 5.]) tensor([ 3.2469, -3.2471], grad_fn=<Ad

In [64]:
print(p)

[3.7451576e-02 1.5107896e-03 5.8836671e-05 2.2881550e-06 3.7443466e-02
 1.5104489e-03 5.8823374e-05 3.7435319e-02 1.5101079e-03 3.7427176e-02
 9.6257919e-01 9.9849010e-01 9.9994123e-01 9.9999774e-01 9.6257108e-01
 9.9848986e-01 9.9994123e-01 9.6256292e-01 9.9848950e-01 9.6255475e-01]


In [65]:
# p - train_y.numpy()

In [66]:
clf = LogisticRegression(random_state=41).fit(train_x, train_y)

clf.predict(test_x)
# clf.score(train_x, train_y)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])